{{- if .Values.repoServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.repoServer.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "argo-cd.repoServer.serviceAccountName" . }}
  namespace: {{ include  "argo-cd.namespace" . }}
  {{- if or .Values.repoServer.serviceAccount.annotations .Values.azure.workloadIdentity.enable }}
  annotations:
    {{- with .Values.repoServer.serviceAccount.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.azure.workloadIdentity.enable }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}
    {{- if .Values.azure.workloadIdentity.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.repoServer.name "name" .Values.repoServer.name) | nindent 4 }}
    {{- with .Values.repoServer.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
