projects:
  guestbook:
    sourceRepos:
      - '*'
    destinations:
      - namespace: guestbook
        server: https://kubernetes.default.svc
    destinationServiceAccounts:
      - server: https://kubernetes.default.svc
        namespace: guestbook
        defaultServiceAccount: guestbook-deployer
      - server: https://kubernetes.default.svc
        namespace: '*'
        defaultServiceAccount: argocd:default-deployer
