# Test VPA for all components
crds:
  keep: false

controller:
  vpa:
    enabled: true

server:
  vpa:
    enabled: true

repoServer:
  vpa:
    enabled: true

applicationSet:
  vpa:
    enabled: true

notifications:
  vpa:
    enabled: true

dex:
  vpa:
    enabled: true

redis:
  vpa:
    enabled: true
