name: "Lint Changelog"

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "charts/*/Chart.yaml"

permissions: {}

jobs:
  validate-changelog:
    name: Validate single changelog entry
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Check artifacthub.io/changes entries
        run: ./scripts/lint-changelog.sh
