name: "Lint Changelog"

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "charts/*/Chart.yaml"

permissions: {}

jobs:
  validate-changelog:
    name: Validate single changelog entry
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Check artifacthub.io/changes entries
        run: ./scripts/lint-changelog.sh
