## Reference: https://github.com/actions/stale
name: Mark stale issues and pull requests
on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  stale:
    permissions:
      contents: read # for actions/stale to read issues and PRs
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Number of days of inactivity before an issue becomes stale
          days-before-stale: 60
          # Number of days of inactivity before a stale issue is closed
          days-before-close: 7
          # Issues with these labels will never be considered stale
          exempt-issue-labels: "on-hold,pinned,security,awaiting-upstream,keep"
          exempt-pr-labels: "on-hold,pinned,security,awaiting-upstream,keep"
          # Comment to post when marking an issue as stale.
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          # Label to use when marking an issue as stale
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
